### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yagizhan49**

### CODE REVIEW

**Comment by PCTipsGR** [comment]
@yagizhan49 what other projects? Currently MOFHDevWorld has no other projects.
Thanks for your PR but I didn't get exactly what do you mean in README. Could you explain please?

**Comment by PCTipsGR** [comment]
Wait what.. 

@mahofficial did u get what @yagizhan49 meant?

**Comment by mahofficial** [comment]
> Wait what..
> 
> @mahofficial did u get what @yagizhan49 meant?

Yep! he added installation instruction and in it he mentioned that for installation instruction refer to other projects of ours

**Comment by PCTipsGR** [comment]
But we don't have other projects, do we?

**Comment by mahofficial** [comment]
> But we don't have other projects, do we?

Ohhh... I got confused between VPT and MOFH lol

**Comment by PCTipsGR** [comment]
I know, and I think that he got confused too, but I can't really be sure. Don't touch anything now please, let it be.

**Comment by PCTipsGR** [comment]
I will rename it to upload via FTP to your server. Issue resolved and PR approved.

**Comment by mahofficial** [comment]
> I know, and I think that he got confused too, but I can't really be sure. Don't touch anything now please, let it be.

I had added now installation instructions and added 

> Download and upload all the files on your web hosting and modify the files as you want but don't remove credits.

**Comment by PCTipsGR** [comment]
oh ok lol, sorry for not checking, it is fine

**Pull request merged**
