### PR TITLE
Fix something

### PR DESCRIPTION
**Pull request by ranakhas**
1. Fix from Your Domain URL to Title
2. Will Improve SEO of template
3. Footer & Logo error fixed

### CODE REVIEW

**Comment by PCTipsGR** [comment]
Have you checked that it works @mahofficial? I am worried about the auto-domain function, if it works properly..

**Comment by mahofficial** [comment]
It works! I tested it. You can check it here view-source:http://trimax.tk/

**Comment by PCTipsGR** [comment]
Okay, if you are sure!

**Comment by mahofficial** [comment]
I tested on the first merge from ranakhas

**Pull request merged**
